os: linux
dist: xenial

language: java

addons:
  artifacts: true
  apt:
    update: true
    packages:
      - libgconf-2-4
      - libxss1
      - libappindicator1
      - libindicator7

before_install:
  # Setup Microsoft Repository
  - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  - sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
  - sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
  - sudo rm microsoft.gpg
  - sudo apt-get update
  - sudo apt install microsoft-edge-dev

before_script:
  # Check Chrome version:
  - google-chrome --version

  # Check Firefox version:
  - firefox --version

  # Check Microsoft Edge Version:
  - microsoft-edge-dev --version  

  # Make chromedriver executable
  - cd template/src/main/resources/drivers/linux/
  - sudo chmod +x chromedriver

script:
  # Run Selenium Suite
  - cd ../../../../.. #Template folder
  - mvn clean -DtestSuite="src/main/resources/suite/testng.xml" test

notifications:
  email:
    recipients:
      - estefafdez@gmail.com
    on_success: always 
    on_failure: always 

  slack:
    - rooms:
      - secure: mEKmNXyP8jEUJBhyN/ydvzSHKnFMTD7dGBvr02a3NGYqPIxOfgXnZYdoZY/WR6879j/92OCMoy6Jn3T+3/zqADShYwMkAUfiP1DOLE8tAO0rCHBtlNvhKRmJen4l7GWukfHP7Bb2ueYf9SWrPWfx8VNYeeaTAcLZeUHXNDb+ZiE7xFftKipUWAWIFG/nak27joQ6dCGqK6tB7SYI2/xmCbYicGybFtgKN1vMszxSue5C3kvAq/9ISnL+rTs63Cn/u9XPXiIxxZytqXIMvI/VcTj+nv34/Q8KJs1w1uGuBdLTSEBsa0lMlZBUU6LyLlAAvJhhUCkW9HpNYhBMtDiyvnlldOukExXIsU83MLhDcPIMZ2ey2+IGPWp+MvM8jssFqF7ne7A7RV6xVL5ZZLUp7IBokh+IDhEo9frDgfdqGD8dcfcj/qgo+7kOHNcI5+IFlbv6ca2T6aAWsMv3e4FkFSPgipDDlWv55hoeTQZZqflFlxJ5KUAGjpZbJ2YW7FzoecOVfI2agedni/VC6E8rYbZDNGbdxkwoCjCJl5v+gGqBJiyIND8a7vBMptbzhG08xMLLlfWzmA7KdpHEInIV0NZEiY9mDb6SOzuaGcyqrtzKZQ0DX0YVzezicUcll2IiSGUuzllhxiPobOGEAuvDFME/HtZ6k1D2nVRbLN/HtSE=
      on_success: always
      on_failure: always
      template:
        - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
        - "Execution time: *%{duration}*"
        - "Commit message: %{commit_message}"
        - "Message: %{message}"